### ISSUE TITLE
how to support float number

### ISSUE THREAD

**Issue by goog** [orangeduck/BuildYourOwnLisp#110]
```number   : /-?[0-9]*[.]?[0-9]+/ ;``` could not, 

```bash
lispy> + 1 2
No you're a + 1 2
<stdin>:1:4: error: expected one of '0123456789', one of '.' or one or more of one of '0123456789' at space
lispy> ^DNo you're a (null)
Segmentation fault
```
I want to add float support.

**Comment by orangeduck** [comment]
Please see some of the following:

https://github.com/orangeduck/mpc/issues/47
https://github.com/orangeduck/mpc/issues/29
https://github.com/orangeduck/mpc/issues/12
https://github.com/orangeduck/mpc/issues/10

**Comment by goog** [comment]
```bash
mpca_lang(MPCA_LANG_DEFAULT,
        "                                                     \
        number   : /-?[0-9]*[.]?[0-9]*/ ;                             \
        operator : '+' | '-' | '*' | '/' | '%';                  \
        expr     : <number> | '(' <operator> <expr>+ ')' ;  \
``` could not parse either.

**Comment by orangeduck** [comment]
Try `number : /-?[0-9]+(\\.[0-9]*)?/ ;`. Your grammar matches the empty string.

**Comment by goog** [comment]
the regular expression you have used is different from others?

**Comment by orangeduck** [comment]
Sorry, I'm not sure I understand. Do you want to know why your regex didn't work? If so - your first regex doesn't work as it will only match numbers with decimal points in. This is because it greedily matches integers, then optionally matches a decimal point, and then requires one or more numbers to follow. For this reason it cannot match normal integers. Your second regex doesn't work because it matches the empty string I.E zero integers, followed by no decimal point, followed by zero integers.

There are several ways to correctly match floats - some of these are listed in the links I posted - one correct way is the regex in my previous comment.

**Comment by zmmaj** [comment]
> Try `number : /-?[0-9]+(\\.[0-9]*)?/ ;`. Your grammar matches the empty string.

That is NOT all . With only this change you can input decimal numbers but output is still wrong eg + 2.2 2 = 4 not 4.2
So, you must change several other thing 
First number declaration from 
 /* Basic */
  **long num;**
  char* err;
  char* sym;
  char* str;

to 
 /* Basic */
  **float num;**
  char* err;
  char* sym;
  char* str;

ELSE: 
**lval* lval_num(long x) {**
  lval* v = malloc(sizeof(lval));
  v->type = LVAL_NUM;
  v->num = x;
  return v;
}
TO
**lval* lval_num(float x) {**
  lval* v = malloc(sizeof(lval));
  v->type = LVAL_NUM;
  v->num = x;
  return v;
}
Still not finished.. In function:
 void lval_print(lval* v) { ....
you must change how will print numbers on output,,, So, change line 
case LVAL_NUM:   printf("%li", v->num); break;
to
case LVAL_NUM:   printf("%3.2f", v->num); break;

Now that is all !
Try now. :)
